name: Backend Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./backend
      run: docker build . --file WebApi/Dockerfile --tag web-api:$(date +%s)
    
