name: Publish image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/publish-image.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/galaktyczne-bambiki/hackcarpathia2025/yocto-builder:master 
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.github_token }}
    steps:
      - name: Setup git credentials
        run: |
          printf "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" > /home/github/.git-credentials

      - uses: actions/checkout@v4

      - name: Sync sources
        working-directory: ./embedded/linux/
        run: |
          repo init -u https://github.com/${{ github.repository }} -m embedded/linux/default.xml
          repo sync -j$(nproc)

      - name: Setup Yocto env
        working-directory: ./embedded/linux/
        run: |
          chmod +x setup-environment
          ./setup-environment build

      - name: Build image
        working-directory: ./embedded/linux/
        shell: bash
        run: |
          source sources/oe-core/oe-init-build-env build
          bitbake medilab-image-update
